window.lookup = {
    events: [
        { value: "", text: "" },
        { value: "Blessing Day", text: "Blessing Day" },
        { value: "Community Learning Opportunity", text: "Community Learning Opportunity" },
        { value: "Cooking & Culture", text: "Cooking & Culture" },
        { value: "Ministry Support Dinner", text: "Ministry Support Dinner" },
        { value: "Welcome Basket Packing Party", text: "Welcome Basket Packing Party" }
    ],
    eventType: [
        { value: "", text: "" },
        { value: "Event", text: "Event" },
        { value: "Ministry", text: "Ministry" },
        { value: "Other", text: "Other" }
    ],
    countries: [
        { value: "", text: "" },
        { value: "United States", text: "United States" },
        { value: "Canada", text: "Canada" },
        { value: "Afghanistan", text: "Afghanistan" },
        { value: "Akrotiri", text: "Akrotiri" },
        { value: "Albania", text: "Albania" },
        { value: "Algeria", text: "Algeria" },
        { value: "American Samoa", text: "American Samoa" },
        { value: "Andorra", text: "Andorra" },
        { value: "Angola", text: "Angola" },
        { value: "Anguilla", text: "Anguilla" },
        { value: "Antarctica", text: "Antarctica" },
        { value: "Antigua and Barbuda", text: "Antigua and Barbuda" },
        { value: "Argentina", text: "Argentina" },
        { value: "Armenia", text: "Armenia" },
        { value: "Aruba", text: "Aruba" },
        { value: "Ashmore and Cartier Islands", text: "Ashmore and Cartier Islands" },
        { value: "Australia", text: "Australia" },
        { value: "Austria", text: "Austria" },
        { value: "Azerbaijan", text: "Azerbaijan" },
        { value: "Bahamas, The", text: "Bahamas, The" },
        { value: "Bahrain", text: "Bahrain" },
        { value: "Bangladesh", text: "Bangladesh" },
        { value: "Barbados", text: "Barbados" },
        { value: "Bassas da India", text: "Bassas da India" },
        { value: "Belarus", text: "Belarus" },
        { value: "Belgium", text: "Belgium" },
        { value: "Belize", text: "Belize" },
        { value: "Benin", text: "Benin" },
        { value: "Bermuda", text: "Bermuda" },
        { value: "Bhutan", text: "Bhutan" },
        { value: "Bolivia", text: "Bolivia" },
        { value: "Bosnia and Herzegovina", text: "Bosnia and Herzegovina" },
        { value: "Botswana", text: "Botswana" },
        { value: "Bouvet Island", text: "Bouvet Island" },
        { value: "Brazil", text: "Brazil" },
        { value: "British Indian Ocean Territory", text: "British Indian Ocean Territory" },
        { value: "British Virgin Islands", text: "British Virgin Islands" },
        { value: "Brunei", text: "Brunei" },
        { value: "Bulgaria", text: "Bulgaria" },
        { value: "Burkina Faso", text: "Burkina Faso" },
        { value: "Burma", text: "Burma" },
        { value: "Burundi", text: "Burundi" },
        { value: "Cambodia", text: "Cambodia" },
        { value: "Cameroon", text: "Cameroon" },
        { value: "Cape Verde", text: "Cape Verde" },
        { value: "Cayman Islands", text: "Cayman Islands" },
        { value: "Central African Republic", text: "Central African Republic" },
        { value: "Chad", text: "Chad" },
        { value: "Chile", text: "Chile" },
        { value: "China", text: "China" },
        { value: "Christmas Island", text: "Christmas Island" },
        { value: "Clipperton Island", text: "Clipperton Island" },
        { value: "Cocos (Keeling) Islands", text: "Cocos (Keeling) Islands" },
        { value: "Colombia", text: "Colombia" },
        { value: "Comoros", text: "Comoros" },
        { value: "Congo, Democratic Republic of the", text: "Congo, Democratic Republic of the" },
        { value: "Congo, Republic of the", text: "Congo, Republic of the" },
        { value: "Cook Islands", text: "Cook Islands" },
        { value: "Coral Sea Islands", text: "Coral Sea Islands" },
        { value: "Costa Rica", text: "Costa Rica" },
        { value: "Cote d'Ivoire", text: "Cote d'Ivoire" },
        { value: "Croatia", text: "Croatia" },
        { value: "Cuba", text: "Cuba" },
        { value: "Cyprus", text: "Cyprus" },
        { value: "Czech Republic", text: "Czech Republic" },
        { value: "Denmark", text: "Denmark" },
        { value: "Dhekelia", text: "Dhekelia" },
        { value: "Djibouti", text: "Djibouti" },
        { value: "Dominica", text: "Dominica" },
        { value: "Dominican Republic", text: "Dominican Republic" },
        { value: "Ecuador", text: "Ecuador" },
        { value: "Egypt", text: "Egypt" },
        { value: "El Salvador", text: "El Salvador" },
        { value: "Equatorial Guinea", text: "Equatorial Guinea" },
        { value: "Eritrea", text: "Eritrea" },
        { value: "Estonia", text: "Estonia" },
        { value: "Ethiopia", text: "Ethiopia" },
        { value: "Europa Island", text: "Europa Island" },
        { value: "Falkland Islands (Islas Malvinas)", text: "Falkland Islands (Islas Malvinas)" },
        { value: "Faroe Islands", text: "Faroe Islands" },
        { value: "Fiji", text: "Fiji" },
        { value: "Finland", text: "Finland" },
        { value: "France", text: "France" },
        { value: "French Guiana", text: "French Guiana" },
        { value: "French Polynesia", text: "French Polynesia" },
        { value: "French Southern and Antarctic Lands", text: "French Southern and Antarctic Lands" },
        { value: "Gabon", text: "Gabon" },
        { value: "Gambia, The", text: "Gambia, The" },
        { value: "Gaza Strip", text: "Gaza Strip" },
        { value: "Georgia", text: "Georgia" },
        { value: "Germany", text: "Germany" },
        { value: "Ghana", text: "Ghana" },
        { value: "Gibraltar", text: "Gibraltar" },
        { value: "Glorioso Islands", text: "Glorioso Islands" },
        { value: "Greece", text: "Greece" },
        { value: "Greenland", text: "Greenland" },
        { value: "Grenada", text: "Grenada" },
        { value: "Guadeloupe", text: "Guadeloupe" },
        { value: "Guam", text: "Guam" },
        { value: "Guatemala", text: "Guatemala" },
        { value: "Guernsey", text: "Guernsey" },
        { value: "Guinea", text: "Guinea" },
        { value: "Guinea-Bissau", text: "Guinea-Bissau" },
        { value: "Guyana", text: "Guyana" },
        { value: "Haiti", text: "Haiti" },
        { value: "Heard Island and McDonald Islands", text: "Heard Island and McDonald Islands" },
        { value: "Holy See (Vatican City)", text: "Holy See (Vatican City)" },
        { value: "Honduras", text: "Honduras" },
        { value: "Hong Kong", text: "Hong Kong" },
        { value: "Hungary", text: "Hungary" },
        { value: "Iceland", text: "Iceland" },
        { value: "India", text: "India" },
        { value: "Indonesia", text: "Indonesia" },
        { value: "Iran", text: "Iran" },
        { value: "Iraq", text: "Iraq" },
        { value: "Ireland", text: "Ireland" },
        { value: "Isle of Man", text: "Isle of Man" },
        { value: "Israel", text: "Israel" },
        { value: "Italy", text: "Italy" },
        { value: "Jamaica", text: "Jamaica" },
        { value: "Jan Mayen", text: "Jan Mayen" },
        { value: "Japan", text: "Japan" },
        { value: "Jersey", text: "Jersey" },
        { value: "Jordan", text: "Jordan" },
        { value: "Juan de Nova Island", text: "Juan de Nova Island" },
        { value: "Kazakhstan", text: "Kazakhstan" },
        { value: "Kenya", text: "Kenya" },
        { value: "Kiribati", text: "Kiribati" },
        { value: "North Korea", text: "North Korea" },
        { value: "South Korea", text: "South Korea" },
        { value: "Kuwait", text: "Kuwait" },
        { value: "Kyrgyzstan", text: "Kyrgyzstan" },
        { value: "Laos", text: "Laos" },
        { value: "Latvia", text: "Latvia" },
        { value: "Lebanon", text: "Lebanon" },
        { value: "Lesotho", text: "Lesotho" },
        { value: "Liberia", text: "Liberia" },
        { value: "Libya", text: "Libya" },
        { value: "Liechtenstein", text: "Liechtenstein" },
        { value: "Lithuania", text: "Lithuania" },
        { value: "Luxembourg", text: "Luxembourg" },
        { value: "Macau", text: "Macau" },
        { value: "Macedonia", text: "Macedonia" },
        { value: "Madagascar", text: "Madagascar" },
        { value: "Malawi", text: "Malawi" },
        { value: "Malaysia", text: "Malaysia" },
        { value: "Maldives", text: "Maldives" },
        { value: "Mali", text: "Mali" },
        { value: "Malta", text: "Malta" },
        { value: "Marshall Islands", text: "Marshall Islands" },
        { value: "Martinique", text: "Martinique" },
        { value: "Mauritania", text: "Mauritania" },
        { value: "Mauritius", text: "Mauritius" },
        { value: "Mayotte", text: "Mayotte" },
        { value: "Mexico", text: "Mexico" },
        { value: "Micronesia, Federated States of", text: "Micronesia, Federated States of" },
        { value: "Moldova", text: "Moldova" },
        { value: "Monaco", text: "Monaco" },
        { value: "Mongolia", text: "Mongolia" },
        { value: "Montserrat", text: "Montserrat" },
        { value: "Morocco", text: "Morocco" },
        { value: "Mozambique", text: "Mozambique" },
        { value: "Namibia", text: "Namibia" },
        { value: "Nauru", text: "Nauru" },
        { value: "Navassa Island", text: "Navassa Island" },
        { value: "Nepal", text: "Nepal" },
        { value: "Netherlands", text: "Netherlands" },
        { value: "Netherlands Antilles", text: "Netherlands Antilles" },
        { value: "New Caledonia", text: "New Caledonia" },
        { value: "New Zealand", text: "New Zealand" },
        { value: "Nicaragua", text: "Nicaragua" },
        { value: "Niger", text: "Niger" },
        { value: "Nigeria", text: "Nigeria" },
        { value: "Niue", text: "Niue" },
        { value: "Norfolk Island", text: "Norfolk Island" },
        { value: "Northern Ireland", text: "Northern Ireland" },
        { value: "Northern Mariana Islands", text: "Northern Mariana Islands" },
        { value: "Norway", text: "Norway" },
        { value: "Oman", text: "Oman" },
        { value: "Pakistan", text: "Pakistan" },
        { value: "Palau", text: "Palau" },
        { value: "Panama", text: "Panama" },
        { value: "Papua New Guinea", text: "Papua New Guinea" },
        { value: "Paracel Islands", text: "Paracel Islands" },
        { value: "Paraguay", text: "Paraguay" },
        { value: "Peru", text: "Peru" },
        { value: "Philippines", text: "Philippines" },
        { value: "Pitcairn Islands", text: "Pitcairn Islands" },
        { value: "Poland", text: "Poland" },
        { value: "Portugal", text: "Portugal" },
        { value: "Puerto Rico", text: "Puerto Rico" },
        { value: "Qatar", text: "Qatar" },
        { value: "Reunion", text: "Reunion" },
        { value: "Romania", text: "Romania" },
        { value: "Russia", text: "Russia" },
        { value: "Rwanda", text: "Rwanda" },
        { value: "Saint Helena", text: "Saint Helena" },
        { value: "Saint Kitts and Nevis", text: "Saint Kitts and Nevis" },
        { value: "Saint Lucia", text: "Saint Lucia" },
        { value: "Saint Pierre and Miquelon", text: "Saint Pierre and Miquelon" },
        { value: "Saint Vincent and the Grenadines", text: "Saint Vincent and the Grenadines" },
        { value: "Samoa", text: "Samoa" },
        { value: "San Marino", text: "San Marino" },
        { value: "Sao Tome and Principe", text: "Sao Tome and Principe" },
        { value: "Saudi Arabia", text: "Saudi Arabia" },
        { value: "Senegal", text: "Senegal" },
        { value: "Serbia and Montenegro", text: "Serbia and Montenegro" },
        { value: "Seychelles", text: "Seychelles" },
        { value: "Sierra Leone", text: "Sierra Leone" },
        { value: "Singapore", text: "Singapore" },
        { value: "Slovakia", text: "Slovakia" },
        { value: "Slovenia", text: "Slovenia" },
        { value: "Solomon Islands", text: "Solomon Islands" },
        { value: "Somalia", text: "Somalia" },
        { value: "South Africa", text: "South Africa" },
        { value: "Spain", text: "Spain" },
        { value: "Sri Lanka", text: "Sri Lanka" },
        { value: "Sudan", text: "Sudan" },
        { value: "Suriname", text: "Suriname" },
        { value: "Sweden", text: "Sweden" },
        { value: "Switzerland", text: "Switzerland" },
        { value: "Syria", text: "Syria" },
        { value: "Taiwan", text: "Taiwan" },
        { value: "Tajikistan", text: "Tajikistan" },
        { value: "Tanzania", text: "Tanzania" },
        { value: "Thailand", text: "Thailand" },
        { value: "Togo", text: "Togo" },
        { value: "Venezuela", text: "Venezuela" },
        { value: "Zimbabwe", text: "Zimbabwe" }
    ],
    states: [
        { value: "", text: "" },
        { value: "Alabama", text: "Alabama" },
        { value: "Alaska", text: "Alaska" },
        { value: "Arizona", text: "Arizona" },
        { value: "Arkansas", text: "Arkansas" },
        { value: "California", text: "California" },
        { value: "Colorado", text: "Colorado" },
        { value: "Connecticut", text: "Connecticut" },
        { value: "Delaware", text: "Delaware" },
        { value: "Florida", text: "Florida" },
        { value: "Georgia", text: "Georgia" },
        { value: "Hawaii", text: "Hawaii" },
        { value: "Idaho", text: "Idaho" },
        { value: "Illinois", text: "Illinois" },
        { value: "Indiana", text: "Indiana" },
        { value: "Iowa", text: "Iowa" },
        { value: "Kansas", text: "Kansas" },
        { value: "Kentucky", text: "Kentucky" },
        { value: "Louisiana", text: "Louisiana" },
        { value: "Maine", text: "Maine" },
        { value: "Maryland", text: "Maryland" },
        { value: "Massachusetts", text: "Massachusetts" },
        { value: "Michigan", text: "Michigan" },
        { value: "Minnesota", text: "Minnesota" },
        { value: "Mississippi", text: "Mississippi" },
        { value: "Missouri", text: "Missouri" },
        { value: "Montana", text: "Montana" },
        { value: "Nebraska", text: "Nebraska" },
        { value: "Nevada", text: "Nevada" },
        { value: "New Hampshire", text: "New Hampshire" },
        { value: "New Jersey", text: "New Jersey" },
        { value: "New Mexico", text: "New Mexico" },
        { value: "New York", text: "New York" },
        { value: "North Carolina", text: "North Carolina" },
        { value: "North Dakota", text: "North Dakota" },
        { value: "Ohio", text: "Ohio" },
        { value: "Oklahoma", text: "Oklahoma" },
        { value: "Oregon", text: "Oregon" },
        { value: "Pennsylvania", text: "Pennsylvania" },
        { value: "Rhode Island", text: "Rhode Island" },
        { value: "South Carolina", text: "South Carolina" },
        { value: "South Dakota", text: "South Dakota" },
        { value: "Tennessee", text: "Tennessee" },
        { value: "Texas", text: "Texas" },
        { value: "Utah", text: "Utah" },
        { value: "Vermont", text: "Vermont" },
        { value: "Virginia", text: "Virginia" },
        { value: "Washington", text: "Washington" },
        { value: "West Virginia", text: "West Virginia" },
        { value: "Wisconsin", text: "Wisconsin" },
        { value: "Wyoming", text: "Wyoming" },
        { value: "Outside US", text: "Outside US" }
    ],
    languages: [
        { value: "", text: "" },
        { value: "English", text: "English" },
        { value: "American Sign Language", text: "American Sign Language" },
        { value: "Amharic (Ethiopia)", text: "Amharic (Ethiopia)" },
        { value: "Amoy", text: "Amoy" },
        { value: "Arabic", text: "Arabic" },
        { value: "Armenian", text: "Armenian" },
        { value: "Azerbaijani", text: "Azerbaijani" },
        { value: "Belarusian", text: "Belarusian" },
        { value: "Bengali", text: "Bengali" },
        { value: "Bikol", text: "Bikol" },
        { value: "Bosnian", text: "Bosnian" },
        { value: "Braille", text: "Braille" },
        { value: "Brazilian Portuguese", text: "Brazilian Portuguese" },
        { value: "Bulgarian", text: "Bulgarian" },
        { value: "Burmese", text: "Burmese" },
        { value: "Canadian French", text: "Canadian French" },
        { value: "Cantonese", text: "Cantonese" },
        { value: "Catalan", text: "Catalan" },
        { value: "Cebuano", text: "Cebuano" },
        { value: "Cham", text: "Cham" },
        { value: "Chamorro (Guam)", text: "Chamorro (Guam)" },
        { value: "Chinese", text: "Chinese" },
        { value: "Chinese–Simplified", text: "Chinese–Simplified" },
        { value: "Chinese–Traditional", text: "Chinese–Traditional" },
        { value: "Chiu Chow", text: "Chiu Chow" },
        { value: "Chow Jo", text: "Chow Jo" },
        { value: "Croatian", text: "Croatian" },
        { value: "Czech", text: "Czech" },
        { value: "Danish", text: "Danish" },
        { value: "Dari", text: "Dari" },
        { value: "Dinka (Sudan)", text: "Dinka (Sudan)" },
        { value: "Dutch", text: "Dutch" },
        { value: "Esperanto", text: "Esperanto" },
        { value: "Estonian", text: "Estonian" },
        { value: "Faroese", text: "Faroese" },
        { value: "Farsi", text: "Farsi" },
        { value: "Fijian", text: "Fijian" },
        { value: "Finnish", text: "Finnish" },
        { value: "Flemish", text: "Flemish" },
        { value: "French", text: "French" },
        { value: "French Creole", text: "French Creole" },
        { value: "Fukienese", text: "Fukienese" },
        { value: "Georgian", text: "Georgian" },
        { value: "German", text: "German" },
        { value: "Greek", text: "Greek" },
        { value: "Gujarati (India)", text: "Gujarati (India)" },
        { value: "Hainanese", text: "Hainanese" },
        { value: "Haitian Creole", text: "Haitian Creole" },
        { value: "Hakka (China)", text: "Hakka (China)" },
        { value: "Hebrew", text: "Hebrew" },
        { value: "Hindi", text: "Hindi" },
        { value: "Hmong", text: "Hmong" },
        { value: "Hungarian", text: "Hungarian" },
        { value: "Ibo (Nigeria)", text: "Ibo (Nigeria)" },
        { value: "Icelandic", text: "Icelandic" },
        { value: "Ilocano", text: "Ilocano" },
        { value: "Ilongo", text: "Ilongo" },
        { value: "Indonesian", text: "Indonesian" },
        { value: "Italian", text: "Italian" },
        { value: "Japanese", text: "Japanese" },
        { value: "Kazakh", text: "Kazakh" },
        { value: "Khmer (Cambodia)", text: "Khmer (Cambodia)" },
        { value: "Kinyarwanda", text: "Kinyarwanda" },
        { value: "Kirundi", text: "Kirundi" },
        { value: "Kmhmu (Laos)", text: "Kmhmu (Laos)" },
        { value: "Korean", text: "Korean" },
        { value: "Kurdish", text: "Kurdish" },
        { value: "Laotian", text: "Laotian" },
        { value: "Latin", text: "Latin" },
        { value: "Latvian", text: "Latvian" },
        { value: "Lithuanian", text: "Lithuanian" },
        { value: "Macedonian", text: "Macedonian" },
        { value: "Malay", text: "Malay" },
        { value: "Malayalam", text: "Malayalam" },
        { value: "Mandarin", text: "Mandarin" },
        { value: "Mandinka", text: "Mandinka" },
        { value: "Marathi (India)", text: "Marathi (India)" },
        { value: "Marshallese", text: "Marshallese" },
        { value: "Mien", text: "Mien" },
        { value: "Mongolian", text: "Mongolian" },
        { value: "Navajo", text: "Navajo" },
        { value: "Nepali", text: "Nepali" },
        { value: "Norwegian", text: "Norwegian" },
        { value: "Nuer (Nilo-Saharan)", text: "Nuer (Nilo-Saharan)" },
        { value: "Oromo (Ethiopia)", text: "Oromo (Ethiopia)" },
        { value: "Palauan", text: "Palauan" },
        { value: "Pampangan", text: "Pampangan" },
        { value: "Pangasinan", text: "Pangasinan" },
        { value: "Pashtu", text: "Pashtu" },
        { value: "Polish", text: "Polish" },
        { value: "Portuguese", text: "Portuguese" },
        { value: "Punjabi", text: "Punjabi" },
        { value: "Quechua", text: "Quechua" },
        { value: "Romanian", text: "Romanian" },
        { value: "Russian", text: "Russian" },
        { value: "Samoan", text: "Samoan" },
        { value: "Serbian", text: "Serbian" },
        { value: "Shona (Zimbabwe)", text: "Shona (Zimbabwe)" },
        { value: "Spanish", text: "Spanish" },
        { value: "Swahili", text: "Swahili" },
        { value: "Swedish", text: "Swedish" },
        { value: "Tagalog", text: "Tagalog" },
        { value: "Tamil", text: "Tamil" },
        { value: "Thai", text: "Thai" },
        { value: "Tigrinya", text: "Tigrinya" },
        { value: "Turkish", text: "Turkish" },
        { value: "Vietnamese", text: "Vietnamese" },
        { value: "Zulu", text: "Zulu" },
        { value: "Unknown", text: "Unknown" },
        { value: "Other", text: "Other" }
    ],
    eslLocations: [
        { value: "", text: "Select a location" },
        { value: "Beechmont Townhomes", text: "Beechmont Townhomes" },
        { value: "Bridge Creek", text: "Bridge Creek" },
        { value: "C3AG", text: "C3AG" },
        { value: "Cornerstone Baptist Church", text: "Cornerstone Baptist Church" },
        { value: "Corydon Baptist Church", text: "Corydon Baptist Church" },
        { value: "DEcAF", text: "DEcAF" },
        { value: "Farmdale Baptist Church", text: "Farmdale Baptist Church" },
        { value: "Gethsemane Baptist Church", text: "Gethsemane Baptist Church" },
        { value: "Hope Place", text: "Hope Place" },
        { value: "Journey Church", text: "Journey Church" },
        { value: "Ninth & O Baptist Church", text: "Ninth & O Baptist Church" },
        { value: "Ormsby Heights Baptist Church", text: "Ormsby Heights Baptist Church" },
        { value: "Shively Baptist Church", text: "Shively Baptist Church" },
        { value: "Other", text: "Other" }
    ],

    maritalStatus: [
        { value: "", text: "" },
        { value: "Single", text: "Single" },
        { value: "Married", text: "Married" },
        { value: "Other", text: "Other" }
    ],

    servingAreas: [
        { value: "", text: "Select a Ministry Area" },
        { value: "Adopt-A-Family", text: "Adopt-A-Family" },
        { value: "Conversation Club", text: "Conversation Club" },
        { value: "English Mentoring", text: "English Mentoring" },
        { value: "ESL Network", text: "ESL Network" },
        { value: "Nations Next Door", text: "Nations Next Door" },
        { value: "Right Start", text: "Right Start" },
        { value: "Translator", text: "Translator" },
        { value: "Welcome Center Use", text: "Welcome Center Use" },
        { value: "Other", text: "Other" }
    ],

    availability: [
        { value: "", text: "" },
        { value: "Sunday Morning", text: "Sunday Morning" },
        { value: "Sunday Afternoon", text: "Sunday Afternoon" },
        { value: "Sunday Evening", text: "Sunday Evening" },
        { value: "Monday Morning", text: "Monday Morning" },
        { value: "Monday Afternoon", text: "Monday Afternoon" },
        { value: "Monday Evening", text: "Monday Evening" },
        { value: "Tuesday Morning", text: "Tuesday Morning" },
        { value: "Tuesday Afternoon", text: "Tuesday Afternoon" },
        { value: "Tuesday Evening", text: "Tuesday Evening" },
        { value: "Wednesday Morning", text: "Wednesday Morning" },
        { value: "Wednesday Afternoon", text: "Wednesday Afternoon" },
        { value: "Wednesday Evening", text: "Wednesday Evening" },
        { value: "Thursday Morning", text: "Thursday Morning" },
        { value: "Thursday Afternoon", text: "Thursday Afternoon" },
        { value: "Thursday Evening", text: "Thursday Evening" },
        { value: "Friday Morning", text: "Friday Morning" },
        { value: "Friday Afternoon", text: "Friday Afternoon" },
        { value: "Friday Evening", text: "Friday Evening" },
        { value: "Saturday Morning", text: "Saturday Morning" },
        { value: "Saturday Afternoon", text: "Saturday Afternoon" },
        { value: "Saturday Evening", text: "Saturday Evening" }
    ],

    howHeard: [
        { value: "", text: "" },
        { value: "Advertisement", text: "Advertisement" },
        { value: "Church", text: "Church" },
        { value: "Friend", text: "Friend" },
        { value: "Google", text: "Google" },
        { value: "Refuge Preview", text: "Refuge Preview" },
        { value: "Seminary", text: "Seminary" },
        { value: "Unleashed App", text: "Unleashed App" },
        { value: "Social Media", text: "Social Media" },
        { value: "Other", text: "Other" }
    ],
    skills: [
        { value: "", text: "" },
        { value: "Administrative", text: "Administrative" },
        { value: "Counseling", text: "Counseling" },
        { value: "Childcare", text: "Childcare" },
        { value: "Communication", text: "Communication" },
        { value: "Community Outreach", text: "Community Outreach" },
        { value: "Compassion", text: "Compassion" },
        { value: "Cultural Awareness", text: "Cultural Awareness" },
        { value: "Cultural Sensitivity", text: "Cultural Sensitivity" },
        { value: "Educational Support", text: "Educational Support" },
        { value: "Engagement", text: "Engagement" },
        { value: "Empathy", text: "Empathy" },
        { value: "ESL", text: "ESL" },
        { value: "Event Planning", text: "Event Planning" },
        { value: "Interpersonal", text: "Interpersonal" },
        { value: "Organizational", text: "Organizational" },
        { value: "Reading Support", text: "Reading Support" },
        { value: "Resource Connection", text: "Resource Connection" },
        { value: "Support", text: "Support" },
        { value: "Teaching", text: "Teaching" },
        { value: "Tutoring", text: "Tutoring" },
        { value: "Other", text: "Other" }
    ],

    salutation: [
        { value: "", text: "" },
        { value: "Mr.", text: "Mr." },
        { value: "Mrs.", text: "Mrs." },
        { value: "Ms.", text: "Ms." },
        { value: "Miss", text: "Miss" },
        { value: "Dr.", text: "Dr." },
        { value: "Prof.", text: "Prof." },
        { value: "Rev.", text: "Rev." },
        { value: "Rev. Dr.", text: "Rev. Dr." },
        { value: "Pastor", text: "Pastor" }
    ],

    relationship: [
        { value: "", text: "" },
        { value: "Parent", text: "Parent" },
        { value: "Spouse", text: "Spouse" },
        { value: "Sibling", text: "Sibling" },
        { value: "Friend", text: "Friend" },
        { value: "Other", text: "Other" }
    ],

    eslInterest: [
        { value: "", text: "" },
        { value: "School Registration", text: "Registering your children for school" },
        { value: "Bible Study", text: "Bible study in Spanish" },
        { value: "Citizenship Class", text: "Citizenship classes" }
    ],

    attendeeType: [
        { value: "", text: "" },
        { value: "Student", text: "Student" },
        { value: "Volunteer", text: "Volunteer" },
        { value: "Child", text: "Child" }
    ],

    studentLevel: [
        { value: "", text: "" },
        { value: "ABC", text: "ABC" },
        { value: "L-1", text: "L-1" },
        { value: "L-2", text: "L-2" },
        { value: "L-3", text: "L-3" },
        { value: "L-4", text: "L-4" },
        { value: "L-5", text: "L-5" }
    ],

    assessmentScore: [
        { value: "", text: "" },
        { value: "1", text: "1" },
        { value: "2", text: "2" },
        { value: "3", text: "3" },
        { value: "4", text: "4" },
        { value: "5", text: "5" }
    ],

    classPlacement: [
        { value: "", text: "" },
        { value: "Beginner", text: "Beginner" },
        { value: "High Beginner", text: "High Beginner" },
        { value: "Intermediate", text: "Intermediate" },
        { value: "High Intermediate", text: "High Intermediate" },
        { value: "Literacy", text: "Literacy" }
    ]

};